export const TRAITS_MAP: any = {
  "head": {
    "common": [
      process.env.PUBLIC_URL + '/traits/head/common/baseball-cap.png',
      process.env.PUBLIC_URL + '/traits/head/common/mobster-hat.png',
      process.env.PUBLIC_URL + '/traits/head/common/snapback-cap.png',
      process.env.PUBLIC_URL + '/traits/head/common/bucket-hat.png',
      process.env.PUBLIC_URL + '/traits/head/common/sailor\'s-hat.png',
      process.env.PUBLIC_URL + '/traits/head/common/beanie.png',
      process.env.PUBLIC_URL + '/traits/head/common/sun-hat.png',
      process.env.PUBLIC_URL + '/traits/head/common/floral-crown.png',
      process.env.PUBLIC_URL + '/traits/head/common/fishing-hat.png',
      process.env.PUBLIC_URL + '/traits/head/common/conical-hat.png',
      process.env.PUBLIC_URL + '/traits/head/common/straw-hat.png',
      process.env.PUBLIC_URL + '/traits/head/common/musketeer\'s-hat.png',
      process.env.PUBLIC_URL + '/traits/head/common/racoon-skin-hat.png',
      process.env.PUBLIC_URL + '/traits/head/common/football-helmet.png',
      process.env.PUBLIC_URL + '/traits/head/common/viking\'s-helmet.png',
      process.env.PUBLIC_URL + '/traits/head/common/graduation-cap.png',
    ],
    "uncommon": [
      process.env.PUBLIC_URL + '/traits/head/uncommon/explorer\'s-hat.png',
      process.env.PUBLIC_URL + '/traits/head/uncommon/headband.png',
      process.env.PUBLIC_URL + '/traits/head/uncommon/fireman\'s-helmet.png',
      process.env.PUBLIC_URL + '/traits/head/uncommon/captain\'s-hat.png',
      process.env.PUBLIC_URL + '/traits/head/uncommon/policeman\'s-cap.png',
      process.env.PUBLIC_URL + '/traits/head/uncommon/pilot\'s-hat.png',
      process.env.PUBLIC_URL + '/traits/head/uncommon/sergeant\'s-hat.png',
      process.env.PUBLIC_URL + '/traits/head/uncommon/laurel-wreath.png',
      process.env.PUBLIC_URL + '/traits/head/uncommon/wizard\'s-hat.png',
      process.env.PUBLIC_URL + '/traits/head/uncommon/judge\'s-wig.png',
      process.env.PUBLIC_URL + '/traits/head/uncommon/umbrella-hat.png',
    ],
    "rare": [
      process.env.PUBLIC_URL + '/traits/head/rare/sultan\'s-turban.png',
      process.env.PUBLIC_URL + '/traits/head/rare/the-croc-hunter.png',
      process.env.PUBLIC_URL + '/traits/head/rare/top-hat.png',
      process.env.PUBLIC_URL + '/traits/head/rare/degen-service-hat.png',
      process.env.PUBLIC_URL + '/traits/head/rare/beer-hat.png',
      process.env.PUBLIC_URL + '/traits/head/rare/pope\'s-mitre.png',
      process.env.PUBLIC_URL + '/traits/head/rare/knight\'s-helmet.png',
    ],
    "superrare": [
      process.env.PUBLIC_URL + '/traits/head/super-rare/tiara.png',
      process.env.PUBLIC_URL + '/traits/head/super-rare/pharaoh\'s-neme.png',
      process.env.PUBLIC_URL + '/traits/head/super-rare/crown.png',
      process.env.PUBLIC_URL + '/traits/head/super-rare/the-artist.png',
      process.env.PUBLIC_URL + '/traits/head/super-rare/roman-helmet.png',
    ],
    "mythic": [
      process.env.PUBLIC_URL + '/traits/head/mythic/harambe\'s-halo.png',
      process.env.PUBLIC_URL + '/traits/head/mythic/space-helmet.png',
    ],
  },
  "clothing": {
    "common": [
      process.env.PUBLIC_URL + '/traits/clothing/common/tie-dye-t-shirt.png',
      process.env.PUBLIC_URL + '/traits/clothing/common/striped-t-shirt.png',
      process.env.PUBLIC_URL + '/traits/clothing/common/hoodie.png',
      process.env.PUBLIC_URL + '/traits/clothing/common/black-t-shirt.png',
      process.env.PUBLIC_URL + '/traits/clothing/common/leather-jacket.png',
      process.env.PUBLIC_URL + '/traits/clothing/common/cheerleader.png',
      process.env.PUBLIC_URL + '/traits/clothing/common/bowling-shirt.png',
      process.env.PUBLIC_URL + '/traits/clothing/common/dress.png',
      process.env.PUBLIC_URL + '/traits/clothing/common/turtleneck.png',
      process.env.PUBLIC_URL + '/traits/clothing/common/wetsuit.png',
      process.env.PUBLIC_URL + '/traits/clothing/common/denim-vest.png',
      process.env.PUBLIC_URL + '/traits/clothing/common/overalls.png',
      process.env.PUBLIC_URL + '/traits/clothing/common/maid\'s-uniform.png',
    ],
    "uncommon": [
      process.env.PUBLIC_URL + '/traits/clothing/uncommon/academy-uniform.png',
      process.env.PUBLIC_URL + '/traits/clothing/uncommon/hawaiin-shirt.png',
      process.env.PUBLIC_URL + '/traits/clothing/uncommon/japanese-uniform.png',
      process.env.PUBLIC_URL + '/traits/clothing/uncommon/pilot\'s-jacket.png',
      process.env.PUBLIC_URL + '/traits/clothing/uncommon/jungle-explorer.png',
      process.env.PUBLIC_URL + '/traits/clothing/uncommon/police-uniform.png',
      process.env.PUBLIC_URL + '/traits/clothing/uncommon/suit.png',
      process.env.PUBLIC_URL + '/traits/clothing/uncommon/turtleneck-suit.png',
    ],
    "rare": [
      process.env.PUBLIC_URL + '/traits/clothing/rare/ski-jacket.png',
      process.env.PUBLIC_URL + '/traits/clothing/rare/nb-ape-red.png',
      process.env.PUBLIC_URL + '/traits/clothing/rare/nb-ape-green.png',
      process.env.PUBLIC_URL + '/traits/clothing/rare/nb-ape-yellow.png',
      process.env.PUBLIC_URL + '/traits/clothing/rare/degen-service-polo.png',
      process.env.PUBLIC_URL + '/traits/clothing/rare/silk-robe.png',
    ],
    "superrare": [
      process.env.PUBLIC_URL + '/traits/clothing/super-rare/fur-coat.png',
      process.env.PUBLIC_URL + '/traits/clothing/super-rare/biggie-sweater.png',
      process.env.PUBLIC_URL + '/traits/clothing/super-rare/space-suit.png',
    ],
    "mythic": [
      process.env.PUBLIC_URL + '/traits/clothing/mythic/prince-charming.png',
    ],
  },
  "mouth": {
    "common": [
      process.env.PUBLIC_URL + '/traits/mouth/common/sandwich.png',
      process.env.PUBLIC_URL + '/traits/mouth/common/banana.png',
      process.env.PUBLIC_URL + '/traits/mouth/common/pizza.png',
      process.env.PUBLIC_URL + '/traits/mouth/common/grilled-cheese.png',
      process.env.PUBLIC_URL + '/traits/mouth/common/soda.png',
      process.env.PUBLIC_URL + '/traits/mouth/common/drool.png',
      process.env.PUBLIC_URL + '/traits/mouth/common/corndog.png',
      process.env.PUBLIC_URL + '/traits/mouth/common/burger.png',
      process.env.PUBLIC_URL + '/traits/mouth/common/hotdog.png',
    ],
    "uncommon": [
      process.env.PUBLIC_URL + '/traits/mouth/uncommon/dirty-fiat.png',
      process.env.PUBLIC_URL + '/traits/mouth/uncommon/ape-le-juice.png',
      process.env.PUBLIC_URL + '/traits/mouth/uncommon/bubblegum.png',
      process.env.PUBLIC_URL + '/traits/mouth/uncommon/pipe.png',
      process.env.PUBLIC_URL + '/traits/mouth/uncommon/eggplant.png',
      process.env.PUBLIC_URL + '/traits/mouth/uncommon/donut.png',
      process.env.PUBLIC_URL + '/traits/mouth/uncommon/sushi.png',
    ],
    "rare": [
      process.env.PUBLIC_URL + '/traits/mouth/rare/smooth-brain.png',
      process.env.PUBLIC_URL + '/traits/mouth/rare/cigar.png',
      process.env.PUBLIC_URL + '/traits/mouth/rare/pv-ape-glue.png',
      process.env.PUBLIC_URL + '/traits/mouth/rare/ape-force-1s.png',
      process.env.PUBLIC_URL + '/traits/mouth/rare/6pc-tendies.png',
    ],
    "superrare": [
      process.env.PUBLIC_URL + '/traits/mouth/super-rare/crayons.png',
      process.env.PUBLIC_URL + '/traits/mouth/super-rare/rainbow-vomit.png',
    ],
    "mythic": [
      process.env.PUBLIC_URL + '/traits/mouth/mythic/golden-tendie.png',
    ],
  },
  "fur/skin": {
    "common": [
      process.env.PUBLIC_URL + '/traits/fur-skin/common/green-peach.png',
      process.env.PUBLIC_URL + '/traits/fur-skin/common/red-peach.png',
      process.env.PUBLIC_URL + '/traits/fur-skin/common/blue-blue.png',
      process.env.PUBLIC_URL + '/traits/fur-skin/common/brown-yellow.png',
      process.env.PUBLIC_URL + '/traits/fur-skin/common/purple-peach.png',
      process.env.PUBLIC_URL + '/traits/fur-skin/common/brown-peach.png',
      process.env.PUBLIC_URL + '/traits/fur-skin/common/green-green.png',
      process.env.PUBLIC_URL + '/traits/fur-skin/common/blue-peach.png',
      process.env.PUBLIC_URL + '/traits/fur-skin/common/red-blue.png',
      process.env.PUBLIC_URL + '/traits/fur-skin/common/purple-purple.png',
    ],
    "uncommon": [
      process.env.PUBLIC_URL + '/traits/fur-skin/uncommon/black-gray.png',
      process.env.PUBLIC_URL + '/traits/fur-skin/uncommon/black-peach.png',
      process.env.PUBLIC_URL + '/traits/fur-skin/uncommon/albino-blue.png',
      process.env.PUBLIC_URL + '/traits/fur-skin/uncommon/albino-peach.png',
    ],
    "rare": [
      process.env.PUBLIC_URL + '/traits/fur-skin/rare/leopard.png',
      process.env.PUBLIC_URL + '/traits/fur-skin/rare/ice.png',
    ],
    "superrare": [
      process.env.PUBLIC_URL + '/traits/fur-skin/super-rare/zombie.png',
      process.env.PUBLIC_URL + '/traits/fur-skin/super-rare/gold.png',
    ],
    "mythic": [
      process.env.PUBLIC_URL + '/traits/fur-skin/mythic/acid-trip.png',
    ],
  },
  "teeth": {
    "common": [
      process.env.PUBLIC_URL + '/traits/teeth/common/wooden-tooth.png',
    ],
    "uncommon": [
      process.env.PUBLIC_URL + '/traits/teeth/uncommon/gold-tooth.png',
    ],
    "rare": [
      process.env.PUBLIC_URL + '/traits/teeth/rare/wooden-teeth.png',
    ],
    "superrare": [
      process.env.PUBLIC_URL + '/traits/teeth/super-rare/gold-teeth.png',
    ],
    "mythic": [
      process.env.PUBLIC_URL + '/traits/teeth/mythic/diamond-teeth.png',
    ],
  },
  "eyewear": {
    "common": [
      process.env.PUBLIC_URL + '/traits/eyewear/common/wayfarer-glasses.png',
      process.env.PUBLIC_URL + '/traits/eyewear/common/aviator-glasses.png',
      process.env.PUBLIC_URL + '/traits/eyewear/common/round-glasses.png',
      process.env.PUBLIC_URL + '/traits/eyewear/common/shutter-shades.png',
    ],
    "uncommon": [
      process.env.PUBLIC_URL + '/traits/eyewear/uncommon/ape-vipers.png',
      process.env.PUBLIC_URL + '/traits/eyewear/uncommon/3d-glasses.png',
    ],
    "rare": [
      process.env.PUBLIC_URL + '/traits/eyewear/rare/heart-glasses.png',
    ],
    "superrare": [
      process.env.PUBLIC_URL + '/traits/eyewear/super-rare/vr-headset.png',
    ]
  },
  "background": {
    "common": [
      process.env.PUBLIC_URL + '/traits/background/common/blue.png',
      process.env.PUBLIC_URL + '/traits/background/common/yellow.png',
      process.env.PUBLIC_URL + '/traits/background/common/green.png',
      process.env.PUBLIC_URL + '/traits/background/common/red.png',
      process.env.PUBLIC_URL + '/traits/background/common/purple.png',
      process.env.PUBLIC_URL + '/traits/background/common/black.png',
      process.env.PUBLIC_URL + '/traits/background/common/teal.png',
    ],
  },
};
